/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCPManagerRole;

import Business.EcoSystem;
import Business.FCPantry.FCPantry;
import Business.FCWarehouse.FCWarehouse;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anujashinde 
 */
public class ContactWarehousePanel extends javax.swing.JPanel {

    /**
     * Creates new form ContactWarehousePanel
     */
    JPanel userProcessContainer;
    UserAccount userAcc;
    EcoSystem ecosystem;
    String WHname;
    String FCPmgname;
    public ContactWarehousePanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        lblRequestedVolunteers.setVisible(false);
        lblVolunteersQty.setVisible(false);
        comboQty.setVisible(false);
        btnSubmitRequest.setVisible(false);
        FCPmgname = userAcc.getEmployee().getName();
        for(FCPantry fcp: ecosystem.getFCPDirectory().getFcpList()){
            if(fcp.getFcpManager().equals(FCPmgname)){
                 WHname = fcp.getFcpWHname();
            }
        }
        setBG();
        populatefields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWarehouseProfileTitle = new javax.swing.JLabel();
        txtWarehouseFoodAdmin = new javax.swing.JTextField();
        lblWarehouseName = new javax.swing.JLabel();
        txtWarehouseName = new javax.swing.JTextField();
        lblWarehouseContact = new javax.swing.JLabel();
        txtWarehouseContact = new javax.swing.JTextField();
        lblWarehouseAdd = new javax.swing.JLabel();
        txtWarehouseAdd = new javax.swing.JTextField();
        lblWarehouseCity = new javax.swing.JLabel();
        txtWarehouseCity = new javax.swing.JTextField();
        lblWarehouseState = new javax.swing.JLabel();
        txtWarehouseState = new javax.swing.JTextField();
        lblWarehouseZip = new javax.swing.JLabel();
        txtWHZip = new javax.swing.JTextField();
        lblWarehouseFoodAdmin = new javax.swing.JLabel();
        comboQty = new javax.swing.JComboBox<>();
        btnSubmitRequest = new javax.swing.JButton();
        lblVolunteersQty = new javax.swing.JLabel();
        lblRequestedVolunteers = new javax.swing.JLabel();
        LabelImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWarehouseProfileTitle.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        lblWarehouseProfileTitle.setForeground(new java.awt.Color(255, 93, 119));
        lblWarehouseProfileTitle.setText("! Food Warehouse !");
        add(lblWarehouseProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        txtWarehouseFoodAdmin.setEditable(false);
        txtWarehouseFoodAdmin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWarehouseFoodAdmin.setEnabled(false);
        txtWarehouseFoodAdmin.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehouseFoodAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarehouseFoodAdminFocusLost(evt);
            }
        });
        add(txtWarehouseFoodAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 137, -1));

        lblWarehouseName.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblWarehouseName.setText("Warehouse Name :");
        add(lblWarehouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 92, -1, -1));

        txtWarehouseName.setEditable(false);
        txtWarehouseName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWarehouseName.setEnabled(false);
        txtWarehouseName.setOpaque(true);
        txtWarehouseName.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehouseName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarehouseNameFocusLost(evt);
            }
        });
        add(txtWarehouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 88, 137, -1));

        lblWarehouseContact.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblWarehouseContact.setText("Phone Number :");
        add(lblWarehouseContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 135, -1, -1));

        txtWarehouseContact.setEditable(false);
        txtWarehouseContact.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWarehouseContact.setEnabled(false);
        txtWarehouseContact.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWarehouseContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarehouseContactFocusLost(evt);
            }
        });
        add(txtWarehouseContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 131, 137, -1));

        lblWarehouseAdd.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblWarehouseAdd.setText("Address :");
        add(lblWarehouseAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 178, -1, -1));

        txtWarehouseAdd.setEditable(false);
        txtWarehouseAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWarehouseAdd.setEnabled(false);
        txtWarehouseAdd.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtWarehouseAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 174, 137, -1));

        lblWarehouseCity.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblWarehouseCity.setText("City :");
        add(lblWarehouseCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 221, -1, -1));

        txtWarehouseCity.setEditable(false);
        txtWarehouseCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWarehouseCity.setEnabled(false);
        txtWarehouseCity.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtWarehouseCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 217, 137, -1));

        lblWarehouseState.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblWarehouseState.setText("State :");
        add(lblWarehouseState, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 264, -1, -1));

        txtWarehouseState.setEditable(false);
        txtWarehouseState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWarehouseState.setEnabled(false);
        txtWarehouseState.setPreferredSize(new java.awt.Dimension(150, 25));
        add(txtWarehouseState, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 260, 137, -1));

        lblWarehouseZip.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblWarehouseZip.setText("Zipcode :");
        add(lblWarehouseZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        txtWHZip.setEditable(false);
        txtWHZip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtWHZip.setEnabled(false);
        txtWHZip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtWHZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWHZipFocusLost(evt);
            }
        });
        add(txtWHZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 137, -1));

        lblWarehouseFoodAdmin.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblWarehouseFoodAdmin.setText("Food Admin :");
        add(lblWarehouseFoodAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 80, -1));

        comboQty.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        comboQty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "10", "20", "30", "40", "50" }));
        add(comboQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 132, -1));

        btnSubmitRequest.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });
        add(btnSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 130, 30));

        lblVolunteersQty.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblVolunteersQty.setText("Number of Volunteers Required :");
        add(lblVolunteersQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        lblRequestedVolunteers.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        lblRequestedVolunteers.setForeground(new java.awt.Color(255, 93, 119));
        lblRequestedVolunteers.setText("Request Volunteers");
        add(lblRequestedVolunteers, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 700));
    }// </editor-fold>//GEN-END:initComponents

       public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {

        }
    }
    private void txtWarehouseFoodAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarehouseFoodAdminFocusLost
        // TODO add your handling code here:
//        if(!(txtWHFCAdmin.getText().matches("^[a-zA-Z]*$"))){
//            lblWHFCAdmin1.setText("Invalid input. Please enter only alphabets.");
//        }
//        else{
//            lblWHFCAdmin1.setText("");
//        }
    }//GEN-LAST:event_txtWarehouseFoodAdminFocusLost

    private void txtWarehouseNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarehouseNameFocusLost
        // TODO add your handling code here:
//        if(!(txtWHname.getText().matches("^[a-zA-Z]*$"))){
//            lblWHname1.setText("Invalid input. Please enter only alphabets");
//        }
//        else{
//            lblWHname1.setText("");
//        }
    }//GEN-LAST:event_txtWarehouseNameFocusLost

    private void txtWarehouseContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarehouseContactFocusLost
        // TODO add your handling code here:
//        if(!(txtWHPhno.getText().matches("^[0-9]*$")) || !(txtWHPhno.getText().length()==10)) {
//            lblWHPhno1.setText("Please enter a valid phone number");
//        }
//        else{
//            lblWHPhno1.setText("");
//
//        }
    }//GEN-LAST:event_txtWarehouseContactFocusLost

    private void txtWHZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWHZipFocusLost
        // TODO add your handling code here:
//        if((txtWHZip.getText().matches("^[a-zA-Z]*$"))){
//            lblWHZip1.setText("Invalid input. Please enter only numbers");
//        }
//        else{
//            lblWHZip1.setText("");
//        }
    }//GEN-LAST:event_txtWHZipFocusLost

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Your request has been sent to Warehouse");
    }//GEN-LAST:event_btnSubmitRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JComboBox<String> comboQty;
    private javax.swing.JLabel lblRequestedVolunteers;
    private javax.swing.JLabel lblVolunteersQty;
    private javax.swing.JLabel lblWarehouseAdd;
    private javax.swing.JLabel lblWarehouseCity;
    private javax.swing.JLabel lblWarehouseContact;
    private javax.swing.JLabel lblWarehouseFoodAdmin;
    private javax.swing.JLabel lblWarehouseName;
    private javax.swing.JLabel lblWarehouseProfileTitle;
    private javax.swing.JLabel lblWarehouseState;
    private javax.swing.JLabel lblWarehouseZip;
    private javax.swing.JTextField txtWHZip;
    private javax.swing.JTextField txtWarehouseAdd;
    private javax.swing.JTextField txtWarehouseCity;
    private javax.swing.JTextField txtWarehouseContact;
    private javax.swing.JTextField txtWarehouseFoodAdmin;
    private javax.swing.JTextField txtWarehouseName;
    private javax.swing.JTextField txtWarehouseState;
    // End of variables declaration//GEN-END:variables

    private void populatefields() {
        for(FCWarehouse fcw : ecosystem.getFCWDirectory().getFcwList()){
            if(fcw.getFcwName().equals(WHname)){
                txtWarehouseName.setText(fcw.getFcwName());
                txtWarehouseContact.setText(fcw.getFcwPhno());
                txtWarehouseAdd.setText(fcw.getFcwAddres());
                txtWarehouseCity.setText(fcw.getFcwCity());
                txtWarehouseState.setText(fcw.getFcwState());
                txtWHZip.setText(fcw.getFcwZipcode());
                txtWarehouseFoodAdmin.setText(fcw.getFcwAdmin());
            }
        }
    }

}
