/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCPManagerRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import userinterface.DonorRole.DonorProfilePanel;
import userinterface.FCAdminRole.FCAdminWorkAreaPanel;
import userinterface.MainJFrame;

/**
 *
 * @author anujashinde
 */
public class FCPManagerWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form FCPManagerWorkAreaPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount account;
    JPanel jp;
    JSplitPane jsp;

    public FCPManagerWorkAreaPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount account, JPanel jp, JSplitPane jsp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecosystem = ecosystem;
        this.jp = jp;
        this.jsp = jsp;

        logoutlogo();
        setLogo();
        setBG();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneFCPManager = new javax.swing.JSplitPane();
        MenubarPanel = new javax.swing.JPanel();
        btnViewFoodRequests = new javax.swing.JButton();
        btnPantryStock = new javax.swing.JButton();
        lblWelcomeFoodPantryManager = new javax.swing.JLabel();
        btnContactWarehouse = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLogoImage = new javax.swing.JLabel();
        WorkAreaPanel = new javax.swing.JPanel();
        LabelImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SplitPaneFCPManager.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        MenubarPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenubarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewFoodRequests.setBackground(new java.awt.Color(255, 93, 119));
        btnViewFoodRequests.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnViewFoodRequests.setText("View Food Requests");
        btnViewFoodRequests.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewFoodRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFoodRequestsActionPerformed(evt);
            }
        });
        MenubarPanel.add(btnViewFoodRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 180, 40));

        btnPantryStock.setBackground(new java.awt.Color(255, 93, 119));
        btnPantryStock.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnPantryStock.setText("Pantry Stock");
        btnPantryStock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPantryStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantryStockActionPerformed(evt);
            }
        });
        MenubarPanel.add(btnPantryStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 120, 40));

        lblWelcomeFoodPantryManager.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        lblWelcomeFoodPantryManager.setForeground(new java.awt.Color(255, 93, 119));
        lblWelcomeFoodPantryManager.setText("! Welcome Food Pantry Manager !");
        MenubarPanel.add(lblWelcomeFoodPantryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        btnContactWarehouse.setBackground(new java.awt.Color(255, 93, 119));
        btnContactWarehouse.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnContactWarehouse.setText("Contact Warehouse");
        btnContactWarehouse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnContactWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactWarehouseActionPerformed(evt);
            }
        });
        MenubarPanel.add(btnContactWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 170, 40));

        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoutMousePressed(evt);
            }
        });
        MenubarPanel.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 43, 41));
        MenubarPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 6, 10, 120));
        MenubarPanel.add(lblLogoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 50));

        SplitPaneFCPManager.setLeftComponent(MenubarPanel);

        WorkAreaPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        WorkAreaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        WorkAreaPanel.add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 650));

        SplitPaneFCPManager.setRightComponent(WorkAreaPanel);

        add(SplitPaneFCPManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 790));
    }// </editor-fold>//GEN-END:initComponents

    public void logoutlogo() {

        try {

            lblLogout.setMinimumSize(new Dimension(50, 60));
            lblLogout.setPreferredSize(new Dimension(50, 60));
            lblLogout.setMaximumSize(new Dimension(50, 60));

            Image img1 = ImageIO.read(getClass().getResource("/Images/Logout.png"));
            Image newimg1 = img1.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);

            lblLogout.setIcon(new ImageIcon(newimg1));

            //IOException is the base class for thrown exceptions
            
        } catch (IOException ex) {
            Logger.getLogger(FCAdminWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void setLogo() {
        try {
            lblLogoImage.setMinimumSize(new Dimension(100, 100));
            lblLogoImage.setPreferredSize(new Dimension(100, 100));
            lblLogoImage.setMaximumSize(new Dimension(100, 100));

            Image img = ImageIO.read(getClass().getResource("/Images/cmnlogo.jpeg"));

            Image newimg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            lblLogoImage.setIcon(new ImageIcon(newimg));
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnViewFoodRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFoodRequestsActionPerformed
        // TODO add your handling code here:
        ViewFoodRequestsPanel objFDreqs = new ViewFoodRequestsPanel(userProcessContainer, ecosystem, account);
        //SplitPane is used to divide two components
        SplitPaneFCPManager.setRightComponent(objFDreqs);
    }//GEN-LAST:event_btnViewFoodRequestsActionPerformed

    private void btnPantryStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantryStockActionPerformed
        // TODO add your handling code here:
        PantryStockPanel objWHI = new PantryStockPanel(userProcessContainer, ecosystem, account);
        //SplitPane is used to divide two components
        SplitPaneFCPManager.setRightComponent(objWHI);
    }//GEN-LAST:event_btnPantryStockActionPerformed

    private void btnContactWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactWarehouseActionPerformed
        // TODO add your handling code here:
        ContactWarehousePanel objConWH = new ContactWarehousePanel(userProcessContainer, ecosystem, account);
        //SplitPane is used to divide two components
        SplitPaneFCPManager.setRightComponent(objConWH);
    }//GEN-LAST:event_btnContactWarehouseActionPerformed

    private void lblLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MainJFrame mjf = new MainJFrame();
            mjf.logout(userProcessContainer, jp, jsp);
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_lblLogoutMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JPanel MenubarPanel;
    private javax.swing.JSplitPane SplitPaneFCPManager;
    private javax.swing.JPanel WorkAreaPanel;
    private javax.swing.JButton btnContactWarehouse;
    private javax.swing.JButton btnPantryStock;
    private javax.swing.JButton btnViewFoodRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogoImage;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblWelcomeFoodPantryManager;
    // End of variables declaration//GEN-END:variables
}
