/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.NGOVolunteer.VolunteerDirectory;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author anujashinde
 */
public class NGOProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOProfilePanel
     */
    JPanel userProcessContainer;
    VolunteerDirectory vold;
    UserAccount userAcc;
    NGODirectory ngod;
    EcoSystem ecosystem;
    String NGOUname;
    String ngoAname;
    boolean validateName = false, validatePhone =false, validateAdd =false, validate; 
    
    public NGOProfilePanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        ngoAname=userAcc.getEmployee().getName();
        NGOUname = userAcc.getUsername();
        btnSubmit.setVisible(false);
        btnCancel.setVisible(false);
        lblNGOConfPassword.setVisible(false);
        txtNGOConfPassword.setVisible(false);
        populateFields();
        setBG();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNGOProfileTitle = new javax.swing.JLabel();
        lblNGOName = new javax.swing.JLabel();
        txtNGOName = new javax.swing.JTextField();
        lblNGOContact = new javax.swing.JLabel();
        txtNGOContact = new javax.swing.JTextField();
        lblNGOAddress = new javax.swing.JLabel();
        txtNGOAddress = new javax.swing.JTextField();
        lblNGOCity = new javax.swing.JLabel();
        txtNGOCity = new javax.swing.JTextField();
        lblNGOState = new javax.swing.JLabel();
        txtNGOState = new javax.swing.JTextField();
        lblNGOZipCode = new javax.swing.JLabel();
        txtNGOZipCode = new javax.swing.JTextField();
        lblNGOAgent = new javax.swing.JLabel();
        txtNGOAgent = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        txtNGOusername = new javax.swing.JTextField();
        lblNGOpassword = new javax.swing.JLabel();
        txtNGOpassword = new javax.swing.JTextField();
        lblNGOConfPassword = new javax.swing.JLabel();
        txtNGOConfPassword = new javax.swing.JTextField();
        lblNGONameError = new javax.swing.JLabel();
        lblNGOphnoError = new javax.swing.JLabel();
        lblNGOaddError = new javax.swing.JLabel();
        lblNGOcityError = new javax.swing.JLabel();
        lblNGOstateError = new javax.swing.JLabel();
        lblNGOzipError = new javax.swing.JLabel();
        lblNGOAgentError = new javax.swing.JLabel();
        lblNGOUsernameError = new javax.swing.JLabel();
        lblNGOpwdError = new javax.swing.JLabel();
        lblNGOConfpwdError = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        LabelImg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNGOProfileTitle.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        lblNGOProfileTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNGOProfileTitle.setText("My Profile");
        add(lblNGOProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        lblNGOName.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOName.setText("Name");
        add(lblNGOName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        txtNGOName.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOName.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOName.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGONameFocusLost(evt);
            }
        });
        add(txtNGOName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 137, -1));

        lblNGOContact.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOContact.setText("Phone Number");
        add(lblNGOContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        txtNGOContact.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOContact.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOContact.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOContactFocusLost(evt);
            }
        });
        add(txtNGOContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 137, -1));

        lblNGOAddress.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOAddress.setText("Address");
        add(lblNGOAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        txtNGOAddress.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOAddress.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOAddress.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOAddressFocusLost(evt);
            }
        });
        add(txtNGOAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 137, -1));

        lblNGOCity.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOCity.setText("City");
        add(lblNGOCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        txtNGOCity.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOCity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOCity.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOCityFocusLost(evt);
            }
        });
        add(txtNGOCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 137, -1));

        lblNGOState.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOState.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOState.setText("State");
        add(lblNGOState, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        txtNGOState.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOState.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOState.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOState.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOStateFocusLost(evt);
            }
        });
        add(txtNGOState, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 137, -1));

        lblNGOZipCode.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOZipCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOZipCode.setText("Zipcode");
        add(lblNGOZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        txtNGOZipCode.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOZipCode.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOZipCode.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOZipCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOZipCodeFocusLost(evt);
            }
        });
        add(txtNGOZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 137, -1));

        lblNGOAgent.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOAgent.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOAgent.setText("NGO Agent");
        add(lblNGOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        txtNGOAgent.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOAgent.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOAgent.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOAgent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOAgentFocusLost(evt);
            }
        });
        add(txtNGOAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 137, -1));

        btnSubmit.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 613, 70, 30));

        btnEdit.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnEdit.setText("Edit Profile");
        btnEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 613, 90, 30));

        lblUsername.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUsername.setText("Username");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        txtNGOusername.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOusername.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOusername.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOusernameFocusLost(evt);
            }
        });
        add(txtNGOusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 137, -1));

        lblNGOpassword.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOpassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOpassword.setText("Password");
        add(lblNGOpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        txtNGOpassword.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOpassword.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOpassword.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOpasswordFocusLost(evt);
            }
        });
        add(txtNGOpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 137, -1));

        lblNGOConfPassword.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNGOConfPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNGOConfPassword.setText("Confirm Password");
        add(lblNGOConfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        txtNGOConfPassword.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtNGOConfPassword.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNGOConfPassword.setPreferredSize(new java.awt.Dimension(150, 25));
        txtNGOConfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNGOConfPasswordFocusLost(evt);
            }
        });
        txtNGOConfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGOConfPasswordActionPerformed(evt);
            }
        });
        add(txtNGOConfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 137, -1));

        lblNGONameError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGONameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 10, 10));

        lblNGOphnoError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOphnoError, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 10, 0));

        lblNGOaddError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOaddError, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 10, 0));

        lblNGOcityError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOcityError, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 10, 0));

        lblNGOstateError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOstateError, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 10, 0));

        lblNGOzipError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOzipError, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 10, 0));

        lblNGOAgentError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOAgentError, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 10, 0));

        lblNGOUsernameError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOUsernameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 10, 0));

        lblNGOpwdError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOpwdError, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 10, 0));

        lblNGOConfpwdError.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(lblNGOConfpwdError, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 10, 0));

        btnCancel.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 613, 60, 30));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -4, 1690, 900));
    }// </editor-fold>//GEN-END:initComponents

    public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1750, 950, java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
            Logger.getLogger(NGOProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void txtNGONameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGONameFocusLost
        // TODO add your handling code here:
        if(!(txtNGOName.getText().matches("^[a-zA-Z]*$"))){
            
            //enter only alphabets in the textfield
            lblNGONameError.setText("Invalid input. Please enter only alphabets");
        }
        else{
            lblNGONameError.setText("");
        }
    }//GEN-LAST:event_txtNGONameFocusLost

    private void txtNGOContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOContactFocusLost
        // TODO add your handling code here:
        if(!(txtNGOContact.getText().matches("^[0-9]*$")) || !(txtNGOContact.getText().length()==10)) {
            
            //entering right phone number is mandetory 
            lblNGOphnoError.setText("Please enter a valid phone number");
        }
        else{
            lblNGOphnoError.setText("");

        }
    }//GEN-LAST:event_txtNGOContactFocusLost

    private void txtNGOAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOAddressFocusLost
        // TODO add your handling code here:
        if(!(txtNGOAddress.getText().matches("^[a-zA-Z]*$"))){
            //put the right and required input 
            lblNGOaddError.setText("Input invalid. Please enter only alphabets");
        }
        else{
            lblNGOaddError.setText("");
        }
    }//GEN-LAST:event_txtNGOAddressFocusLost

    private void txtNGOCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOCityFocusLost
        // TODO add your handling code here:
        if(!(txtNGOCity.getText().matches("^[a-zA-Z]*$"))){
            
            //city should be in alphabets 
            lblNGOcityError.setText("Input invalid. Please enter only alphabets");
        }
        else{
            lblNGOcityError.setText("");
        }
    }//GEN-LAST:event_txtNGOCityFocusLost

    private void txtNGOStateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOStateFocusLost
        // TODO add your handling code here:
        if(!(txtNGOState.getText().matches("^[a-zA-Z]*$"))){
            
            //state should be in alphabets 
            lblNGOstateError.setText("Input invalid. Please enter only alphabets");
        }
        else{
            lblNGOstateError.setText("");
        }
    }//GEN-LAST:event_txtNGOStateFocusLost

    private void txtNGOZipCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOZipCodeFocusLost
        // TODO add your handling code here:
        if((txtNGOZipCode.getText().matches("^[a-zA-Z]*$"))){
            
            //Zip Code should be in numbers 
            lblNGOzipError.setText("Input invalid. Please enter only numbers");
        }
        else{
            lblNGOzipError.setText("");
        }
    }//GEN-LAST:event_txtNGOZipCodeFocusLost

    private void txtNGOAgentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOAgentFocusLost
        // TODO add your handling code here:
        if ((!txtNGOAgent.getText().isEmpty()) && !txtNGOAgent.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {
            lblNGOAgentError.setText( "Please provide valid email address!!");
        }
        else{
            lblNGOAgentError.setText("");
        }
    }//GEN-LAST:event_txtNGOAgentFocusLost

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!nullCheck()){
            ArrayList<NGO> ngoList = ecosystem.getNgoDir().getNgoList();
            for(NGO d: ngoList)
            {
                if(d.getNgoAccount().getUsername().equals(NGOUname))
                {
                      //The get method returns the variable name's value.
                     //The name variable is given a parameter (newName), which is assigned via the set method.
                    d.setNgoName(txtNGOName.getText());
                    d.setNgoPhno(txtNGOContact.getText());
                    d.setNgoAgent(txtNGOAgent.getText());
                    d.setNgoAddress(txtNGOAddress.getText());
                    d.setNgoCity(txtNGOCity.getText());
                    d.setNgoState(txtNGOState.getText());
                    d.setNgoZipcode(txtNGOZipCode.getText());
                    UserAccount ngoAccount=new UserAccount();
                    ngoAccount.setUsername(txtNGOusername.getText());
                    ngoAccount.setPassword(txtNGOpassword.getText());
                }
            }
            // ecosystem.setFCWDirectory(fcwList);
            ngod = ecosystem.getNgoDir();
            ecosystem.setNgoDir(ngod);
             //JOptionPane.showMessageDialog is used to create an information-message dialog titled "Message"
             //after clicking on submit the profile will be updated successfully 
            JOptionPane.showMessageDialog(this, "Profile updated successfully");
            disableFields();
        }
        else{
            //all fields should be field 
            JOptionPane.showMessageDialog(this, "All fields are mandatory!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        enablefields();
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNGOusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOusernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOusernameFocusLost

    private void txtNGOpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOpasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOpasswordFocusLost

    private void txtNGOConfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNGOConfPasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOConfPasswordFocusLost

    private void txtNGOConfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGOConfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGOConfPasswordActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        disableFields();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void populateFields() {
        for(NGO d: ecosystem.getNgoDir().getNgoList()){
            if(d.getNgoAgent().equals(ngoAname)){
            txtNGOName.setText(d.getNgoName());
            txtNGOName.setEnabled(false);
            txtNGOContact.setText(d.getNgoPhno());
            txtNGOContact.setEnabled(false);
            txtNGOAgent.setText(d.getNgoAgent());
            txtNGOAgent.setEnabled(false);
            txtNGOAddress.setText(d.getNgoAddress());
            txtNGOAddress.setEnabled(false);
            txtNGOCity.setText(d.getNgoCity());
            txtNGOCity.setEnabled(false);
            txtNGOState.setText(d.getNgoState());
            txtNGOState.setEnabled(false);
            txtNGOZipCode.setText(d.getNgoZipcode());
            txtNGOZipCode.setEnabled(false);
            txtNGOusername.setText(d.getNgoAccount().getUsername());
            txtNGOusername.setEnabled(false);
            txtNGOpassword.setText(d.getNgoAccount().getPassword());
            txtNGOpassword.setEnabled(false);
            }
        }
    }
    
    private void enablefields() {
        //setEnabled(true) enables the button
        txtNGOName.setEnabled(true);
        txtNGOContact.setEnabled(true);
        txtNGOAgent.setEnabled(true);
        txtNGOAddress.setEnabled(true);
        txtNGOCity.setEnabled(true);
        txtNGOState.setEnabled(true);
        txtNGOZipCode.setEnabled(true);
        txtNGOusername.setEnabled(true);
        txtNGOpassword.setEnabled(true);
        btnSubmit.setVisible(true);
        btnCancel.setVisible(true);
        lblNGOConfPassword.setVisible(true);
        txtNGOConfPassword.setVisible(true);
    }
    
    private void disableFields() {
          //setEnabled(false) disable the button
        txtNGOName.setEnabled(false);
        txtNGOContact.setEnabled(false);
        txtNGOAgent.setEnabled(false);
        txtNGOAddress.setEnabled(false);
        txtNGOCity.setEnabled(false);
        txtNGOState.setEnabled(false);
        txtNGOZipCode.setEnabled(false);
        txtNGOusername.setEnabled(false);
        txtNGOpassword.setEnabled(false);
        btnSubmit.setVisible(false);
        btnCancel.setVisible(false);
        lblNGOConfPassword.setVisible(false);
        txtNGOConfPassword.setVisible(false);
        lblNGONameError.setText("");
        lblNGOphnoError.setText("");
        lblNGOAgentError.setText("");
        lblNGOaddError.setText("");
        lblNGOcityError.setText("");
        lblNGOstateError.setText("");
        lblNGOzipError.setText("");
        lblNGOUsernameError.setText("");
        lblNGOpwdError.setText("");
        lblNGOConfpwdError.setText("");
    }
 
    private boolean nullCheck() {
        if(txtNGOName.getText().length()!=0 && txtNGOContact.getText().length()!=0 && txtNGOAgent.getText().length()!=0 
                && txtNGOAddress.getText().length()!=0 && txtNGOCity.getText().length()!=0 && txtNGOState.getText().length()!=0
                && txtNGOZipCode.getText().length()!=0 && txtNGOusername.getText().length()!=0 && txtNGOpassword.getText().length()!=0
                && txtNGOConfPassword.getText().length()!=0 )
        {
            return false;
        }
        else return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblNGOAddress;
    private javax.swing.JLabel lblNGOAgent;
    private javax.swing.JLabel lblNGOAgentError;
    private javax.swing.JLabel lblNGOCity;
    private javax.swing.JLabel lblNGOConfPassword;
    private javax.swing.JLabel lblNGOConfpwdError;
    private javax.swing.JLabel lblNGOContact;
    private javax.swing.JLabel lblNGOName;
    private javax.swing.JLabel lblNGONameError;
    private javax.swing.JLabel lblNGOProfileTitle;
    private javax.swing.JLabel lblNGOState;
    private javax.swing.JLabel lblNGOUsernameError;
    private javax.swing.JLabel lblNGOZipCode;
    private javax.swing.JLabel lblNGOaddError;
    private javax.swing.JLabel lblNGOcityError;
    private javax.swing.JLabel lblNGOpassword;
    private javax.swing.JLabel lblNGOphnoError;
    private javax.swing.JLabel lblNGOpwdError;
    private javax.swing.JLabel lblNGOstateError;
    private javax.swing.JLabel lblNGOzipError;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtNGOAddress;
    private javax.swing.JTextField txtNGOAgent;
    private javax.swing.JTextField txtNGOCity;
    private javax.swing.JTextField txtNGOConfPassword;
    private javax.swing.JTextField txtNGOContact;
    private javax.swing.JTextField txtNGOName;
    private javax.swing.JTextField txtNGOState;
    private javax.swing.JTextField txtNGOZipCode;
    private javax.swing.JTextField txtNGOpassword;
    private javax.swing.JTextField txtNGOusername;
    // End of variables declaration//GEN-END:variables
}
