/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import userinterface.DonorRole.DonorProfilePanel;
import userinterface.MainJFrame;

/**
 *
 * @author anujashinde
 */
public class NGOWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOWorkAreaPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    JPanel jp;
    JSplitPane jsp;
    public NGOWorkAreaPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc, JPanel jp, JSplitPane jsp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc =userAcc;
        this.jp = jp;
        this.jsp = jsp;
        setLogo();
        setBG();
        logoutlogo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneDon = new javax.swing.JSplitPane();
        MenubarPanel = new javax.swing.JPanel();
        btnManageVolunteers = new javax.swing.JButton();
        btnNGOProfile = new javax.swing.JButton();
        lblWelcomeNGOTitle = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        logoImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        WorkAreaPanel = new javax.swing.JPanel();
        LabelImg = new javax.swing.JLabel();

        SplitPaneDon.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        MenubarPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenubarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageVolunteers.setBackground(new java.awt.Color(255, 93, 119));
        btnManageVolunteers.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnManageVolunteers.setText("Manage Volunteers");
        btnManageVolunteers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageVolunteers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVolunteersActionPerformed(evt);
            }
        });
        MenubarPanel.add(btnManageVolunteers, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 160, 30));

        btnNGOProfile.setBackground(new java.awt.Color(255, 93, 119));
        btnNGOProfile.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnNGOProfile.setText("My Profile");
        btnNGOProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNGOProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNGOProfileActionPerformed(evt);
            }
        });
        MenubarPanel.add(btnNGOProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 90, 30));

        lblWelcomeNGOTitle.setBackground(new java.awt.Color(105, 158, 208));
        lblWelcomeNGOTitle.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        lblWelcomeNGOTitle.setForeground(new java.awt.Color(255, 93, 119));
        lblWelcomeNGOTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeNGOTitle.setText("! Welcome NGO !");
        MenubarPanel.add(lblWelcomeNGOTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 6, -1, -1));

        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbllogoutMousePressed(evt);
            }
        });
        MenubarPanel.add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 43, 41));
        MenubarPanel.add(logoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, 60));
        MenubarPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 6, -1, 110));

        SplitPaneDon.setLeftComponent(MenubarPanel);

        WorkAreaPanel.setPreferredSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
        WorkAreaPanel.setLayout(WorkAreaPanelLayout);
        WorkAreaPanelLayout.setHorizontalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        );
        WorkAreaPanelLayout.setVerticalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
        );

        SplitPaneDon.setRightComponent(WorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneDon, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneDon, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
         public void setLogo() {
        try {
            logoImage.setMinimumSize(new Dimension(100, 100));
            logoImage.setPreferredSize(new Dimension(100, 100));
            logoImage.setMaximumSize(new Dimension(100, 100));

            Image img = ImageIO.read(getClass().getResource("/Images/cmnlogo.jpeg"));

            Image newimg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            logoImage.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
         
    private void btnManageVolunteersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVolunteersActionPerformed
        // TODO add your handling code here:
        ManageVolunteerPanel objViewDon = new ManageVolunteerPanel(userProcessContainer,ecosystem,userAcc, jp, jsp);
        SplitPaneDon.setRightComponent(objViewDon);
    }//GEN-LAST:event_btnManageVolunteersActionPerformed

    private void btnNGOProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNGOProfileActionPerformed
        // TODO add your handling code here:
        NGOProfilePanel objNGOProf = new NGOProfilePanel(userProcessContainer,ecosystem,userAcc);
        SplitPaneDon.setRightComponent(objNGOProf);
    }//GEN-LAST:event_btnNGOProfileActionPerformed

    private void lbllogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MainJFrame mjf = new MainJFrame();
            mjf.logout(userProcessContainer, jp, jsp);
        } catch (IOException ex) {
            Logger.getLogger(NGOWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbllogoutMousePressed

    public void setBG() {
        try {
        
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1450, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void logoutlogo() {

        try {
           //setMinimum is used to set minimum size 
            lbllogout.setMinimumSize(new Dimension(50,60));
            //setPreferredSize is used to set preferred size
            lbllogout.setPreferredSize(new Dimension(50,60));
            //setMaximum is used to set maximum size
            lbllogout.setMaximumSize(new Dimension(50,60));
            
            Image img1 = ImageIO.read(getClass().getResource("/Images/Logout.png"));
            Image newimg1 = img1.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);

            lbllogout.setIcon(new ImageIcon(newimg1));
            
            
        } catch (IOException ex) {
            Logger.getLogger(NGOWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JPanel MenubarPanel;
    private javax.swing.JSplitPane SplitPaneDon;
    private javax.swing.JPanel WorkAreaPanel;
    private javax.swing.JButton btnManageVolunteers;
    private javax.swing.JButton btnNGOProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWelcomeNGOTitle;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel logoImage;
    // End of variables declaration//GEN-END:variables
}
