/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCAdminRole;

import Business.Donation.Donation;
import Business.EcoSystem;
import Business.FCWarehouse.FCWarehouse;
import Business.NGOVolunteer.Volunteer;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anujashinde
 */
public class DonationRequestsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDonations
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    String volname;
    String WHname;
    String city;
    public DonationRequestsPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAcc = userAcc;
        String FCAname=userAcc.getEmployee().getName();
        System.out.println(FCAname);
        WHname= ecosystem.getFCWDirectory().getWHname(FCAname);
        for(FCWarehouse f: ecosystem.getFCWDirectory().getFcwList()){
            if(f.getFcwName().equals(WHname)){
                city=f.getFcwCity();
            }
        }
        ArrayList<String> VolunteerList = new ArrayList();
        for (Volunteer vol : ecosystem.getVolDir().getVolunteerList()){
            if(vol.getVolCity().equals(city) && vol.getVolAvail().equals("Yes")){
            VolunteerList.add(vol.getVolName());
            }
        }
        comboVolunteer.setModel(new DefaultComboBoxModel<String>(VolunteerList.toArray(new String[0])));
        populateTable();
        setBG();
        makeTableTransparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDonProfileTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonationRequests = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        lblFoodDonationID = new javax.swing.JLabel();
        txtDonationReqID = new javax.swing.JTextField();
        lblDRid1 = new javax.swing.JLabel();
        comboVolunteer = new javax.swing.JComboBox<>();
        btnSendRequest = new javax.swing.JButton();
        lblDonProfileTitle1 = new javax.swing.JLabel();
        LabelImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDonProfileTitle.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        lblDonProfileTitle.setForeground(new java.awt.Color(255, 93, 119));
        lblDonProfileTitle.setText("! Donation Requests !");
        add(lblDonProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 14, -1, -1));

        tblDonationRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Donation Id", "Food Item", "Quantity", "Warehouse", "Status"
            }
        ));
        tblDonationRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDonationRequestsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDonationRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1030, 153));

        btnAssign.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 80, 30));

        lblFoodDonationID.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblFoodDonationID.setText("Donation Id :");
        add(lblFoodDonationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        txtDonationReqID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDonationReqID.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDonationReqID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDonationReqIDFocusLost(evt);
            }
        });
        txtDonationReqID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDonationReqIDKeyReleased(evt);
            }
        });
        add(txtDonationReqID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 137, -1));

        lblDRid1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblDRid1.setText("Assign Volunteer :");
        add(lblDRid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        comboVolunteer.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        comboVolunteer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 140, -1));

        btnSendRequest.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnSendRequest.setText("Send a Request to Volunteer");
        btnSendRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });
        add(btnSendRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 220, 30));

        lblDonProfileTitle1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblDonProfileTitle1.setForeground(new java.awt.Color(255, 93, 119));
        lblDonProfileTitle1.setText("Assign a Volunteer :");
        add(lblDonProfileTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));
        add(LabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 850));
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtDonationReqIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDonationReqIDFocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtDonationReqIDFocusLost

    private void txtDonationReqIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDonationReqIDKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDonationReqIDKeyReleased

    public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1650, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(ViewPantryItemsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
  public void makeTableTransparent() {
        tblDonationRequests.setOpaque(false);
        ((DefaultTableCellRenderer) tblDonationRequests.getDefaultRenderer(Object.class)).setOpaque(false);
        tblDonationRequests.setShowGrid(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.WHITE);

        for (int i = 0; i < tblDonationRequests.getModel().getColumnCount(); i++) {
            tblDonationRequests.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblDonationRequests.getSelectedRow();
        if(selectedRowIndex < 0){
            //select the request you want 
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDonationRequests.getModel();
        Donation selectedD = (Donation)model.getValueAt(selectedRowIndex, 0);
        txtDonationReqID.setText(selectedD.getDonatId());
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        String Donid=txtDonationReqID.getText();
        for(Donation d: ecosystem.getDonatDirectory().getDonatList()){
            volname= comboVolunteer.getSelectedItem().toString();
            d.setDonatVol(volname);
            d.setDonatStatus("Assigned to Volunteer");
        }
        for(Volunteer v:ecosystem.getVolDir().getVolunteerList()){
            if(v.getVolName().equals(volname)){
                v.setVolAvail("No");
            }
        }
        //work assigned to volunteer
        JOptionPane.showMessageDialog(this, "Pickup Request Assigned to Volunteer Successfully!");
        populateTable();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void tblDonationRequestsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonationRequestsMousePressed
        // TODO add your handling code here:
        tblDonationRequests.setSelectionForeground(Color.BLUE);
    }//GEN-LAST:event_tblDonationRequestsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JComboBox<String> comboVolunteer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDRid1;
    private javax.swing.JLabel lblDonProfileTitle;
    private javax.swing.JLabel lblDonProfileTitle1;
    private javax.swing.JLabel lblFoodDonationID;
    private javax.swing.JTable tblDonationRequests;
    private javax.swing.JTextField txtDonationReqID;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblDonationRequests.getModel();
        model.setRowCount(0);
        for(Donation dt: ecosystem.getDonatDirectory().getDonatList()){
            if(dt.getDonatWHname().equals(WHname)){
           Object[] row = new Object[5];
           row[0] =dt;
           row[1] =dt.getDonatFooditem();
           row[2] =dt.getDonatFoodQuant();
           row[3] =dt.getDonatWHname();
           row[4] =dt.getDonatStatus();
           model.addRow(row);
            }
        } 
    }
}
