/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.FCAdminRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import userinterface.DonorRole.DonorProfilePanel;
import userinterface.MainJFrame;

/**
 *
 * @author anujashinde
 */
public class FCAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form FCAdminWorkAreaPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAccount;
    JPanel jp;
    JSplitPane jsp;
    public FCAdminWorkAreaPanel(JPanel userProcessContainer,EcoSystem ecosystem, UserAccount userAccount, JPanel jp, JSplitPane jsp) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        this.jp = jp;
        this.jsp = jsp;
        setBG();
        logoutlogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneFCAdmin = new javax.swing.JSplitPane();
        MenubarPanel = new javax.swing.JPanel();
        btnViewDonationRequests = new javax.swing.JButton();
        btnManagePantryItems = new javax.swing.JButton();
        btnManageVolunteers = new javax.swing.JButton();
        lblWelcomeFoodAdmin = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        WorkAreaPanel = new javax.swing.JPanel();
        LabelImg = new javax.swing.JLabel();

        SplitPaneFCAdmin.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        MenubarPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenubarPanel.setToolTipText("");

        btnViewDonationRequests.setBackground(new java.awt.Color(255, 93, 119));
        btnViewDonationRequests.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnViewDonationRequests.setText("View Donation Requests");
        btnViewDonationRequests.setToolTipText("");
        btnViewDonationRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonationRequestsActionPerformed(evt);
            }
        });

        btnManagePantryItems.setBackground(new java.awt.Color(255, 93, 119));
        btnManagePantryItems.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnManagePantryItems.setText("Manage Pantry Items");
        btnManagePantryItems.setToolTipText("");
        btnManagePantryItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePantryItemsActionPerformed(evt);
            }
        });

        btnManageVolunteers.setBackground(new java.awt.Color(255, 93, 119));
        btnManageVolunteers.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnManageVolunteers.setText("Manage Volunteers");
        btnManageVolunteers.setToolTipText("");
        btnManageVolunteers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVolunteersActionPerformed(evt);
            }
        });

        lblWelcomeFoodAdmin.setFont(new java.awt.Font("Georgia", 1, 29)); // NOI18N
        lblWelcomeFoodAdmin.setForeground(new java.awt.Color(255, 93, 119));
        lblWelcomeFoodAdmin.setText("! Welcome, Food Admin !");

        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbllogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout MenubarPanelLayout = new javax.swing.GroupLayout(MenubarPanel);
        MenubarPanel.setLayout(MenubarPanelLayout);
        MenubarPanelLayout.setHorizontalGroup(
            MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenubarPanelLayout.createSequentialGroup()
                .addGroup(MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenubarPanelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(lblWelcomeFoodAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MenubarPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnManagePantryItems)
                        .addGap(56, 56, 56)
                        .addComponent(btnViewDonationRequests)
                        .addGap(48, 48, 48)
                        .addComponent(btnManageVolunteers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        MenubarPanelLayout.setVerticalGroup(
            MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenubarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenubarPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblWelcomeFoodAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenubarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManagePantryItems)
                            .addComponent(btnViewDonationRequests)
                            .addComponent(btnManageVolunteers)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        SplitPaneFCAdmin.setLeftComponent(MenubarPanel);

        WorkAreaPanel.setPreferredSize(new java.awt.Dimension(1000, 700));

        LabelImg.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
        WorkAreaPanel.setLayout(WorkAreaPanelLayout);
        WorkAreaPanelLayout.setHorizontalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
        );
        WorkAreaPanelLayout.setVerticalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                .addComponent(LabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SplitPaneFCAdmin.setRightComponent(WorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneFCAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneFCAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDonationRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonationRequestsActionPerformed
        // TODO add your handling code here:
        DonationRequestsPanel objDonReq =  new DonationRequestsPanel(userProcessContainer,ecosystem,userAccount);
        //SplitPane is used to divide two components
        SplitPaneFCAdmin.setRightComponent(objDonReq);
    }//GEN-LAST:event_btnViewDonationRequestsActionPerformed

    private void btnManagePantryItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePantryItemsActionPerformed
        // TODO add your handling code here:
        ManagePantryItemsPanel objWHI = new ManagePantryItemsPanel(userProcessContainer,ecosystem,userAccount);
        //SplitPane is used to divide two components
        SplitPaneFCAdmin.setRightComponent(objWHI);
    }//GEN-LAST:event_btnManagePantryItemsActionPerformed

    private void btnManageVolunteersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVolunteersActionPerformed
        // TODO add your handling code here:
        ManageVolunteerPanel objVol =  new ManageVolunteerPanel(userProcessContainer,ecosystem,userAccount);
        //SplitPane is used to divide two components
        SplitPaneFCAdmin.setRightComponent(objVol);
    }//GEN-LAST:event_btnManageVolunteersActionPerformed

    private void lbllogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MainJFrame mjf = new MainJFrame();
            mjf.logout(userProcessContainer, jp, jsp);
        } catch (IOException ex) {
            Logger.getLogger(FCAdminWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbllogoutMousePressed

    public void logoutlogo() {

        try {
           
            lbllogout.setMinimumSize(new Dimension(50,60));
            lbllogout.setPreferredSize(new Dimension(50,60));
            lbllogout.setMaximumSize(new Dimension(50,60));
            
            Image img1 = ImageIO.read(getClass().getResource("/Images/Logout.png"));
            Image newimg1 = img1.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);

            lbllogout.setIcon(new ImageIcon(newimg1));
            
            
        } catch (IOException ex) {
            Logger.getLogger(FCAdminWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
  public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JPanel MenubarPanel;
    private javax.swing.JSplitPane SplitPaneFCAdmin;
    private javax.swing.JPanel WorkAreaPanel;
    private javax.swing.JButton btnManagePantryItems;
    private javax.swing.JButton btnManageVolunteers;
    private javax.swing.JButton btnViewDonationRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWelcomeFoodAdmin;
    private javax.swing.JLabel lbllogout;
    // End of variables declaration//GEN-END:variables
}
