

package userinterface.RestaurantAdminRole;



import javax.swing.JPanel;

/**
 *
 * @author  anujakale
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer) {
        
        //Initcomponents is a method that NetBeans Swing Designer creates to initialize components
        initComponents();
        this.userProcessContainer = userProcessContainer;
      
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestoAdminTitle = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRestoAdminTitle.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        lblRestoAdminTitle.setForeground(new java.awt.Color(255, 93, 119));
        lblRestoAdminTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestoAdminTitle.setText("! My Work Area - Adminstrative Role !");
        add(lblRestoAdminTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        userJButton.setBackground(new java.awt.Color(255, 93, 119));
        userJButton.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        userJButton.setText("Manage Restaurant Info");
        userJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 190, 40));

        manageEmployeeJButton.setBackground(new java.awt.Color(255, 93, 119));
        manageEmployeeJButton.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        manageEmployeeJButton.setText("Manage menu");
        manageEmployeeJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 190, 40));

        manageOrganizationJButton.setBackground(new java.awt.Color(255, 93, 119));
        manageOrganizationJButton.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        manageOrganizationJButton.setText("Manage Orders");
        manageOrganizationJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 190, 40));

        enterpriseLabel.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enterpriseLabel.setText("Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        valueLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel lblRestoAdminTitle;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
