/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DonorRole;

import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Donation.Donation;
import Business.Donation.DonationDirectory;
import Business.Donor.Donor;
import Business.EcoSystem;
import Business.FCWarehouse.FCWarehouse;
import Business.UserAccount.UserAccount;

/**
 *
 * @author dristidani
 */
public class DonateNowPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonateNowPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAcc;
    DonationDirectory donatD;
    String donUName;
    String donName;
    String donState;
    
    public DonateNowPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem =ecosystem;
        this.userAcc = userAcc;
        donUName = userAcc.getUsername();
        donName  = userAcc.getEmployee().getName();
        if(ecosystem.getDonatDirectory()== null){
         ecosystem.setDonatDirectory(new DonationDirectory());
        }
        String donState = ecosystem.getDonDir().getdonState(donUName);
        ArrayList<String> CityList = new ArrayList<String>();
        for (FCWarehouse fcw : ecosystem.getFCWDirectory().getFcwList()){
            if(fcw.getFcwState().equals(donState)){
                CityList.add(fcw.getFcwCity());
            }
        }         
        comboCity.setModel(new DefaultComboBoxModel<String>(CityList.toArray(new String[0])));
        
        setBG();
       // setLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDonateTitle = new javax.swing.JLabel();
        lblDonateFoodItem = new javax.swing.JLabel();
        lblDonateFoodQty = new javax.swing.JLabel();
        txtDonateFoodItem = new javax.swing.JTextField();
        sdQuan = new javax.swing.JSlider();
        lblDonatePickupAdd = new javax.swing.JLabel();
        chkAddress = new javax.swing.JCheckBox();
        lblDonateFoodAddress = new javax.swing.JLabel();
        txtDadd = new javax.swing.JTextField();
        lblPickupCity = new javax.swing.JLabel();
        txtDcity = new javax.swing.JTextField();
        lblPickupState = new javax.swing.JLabel();
        txtDstate = new javax.swing.JTextField();
        lblPickupZipCode = new javax.swing.JLabel();
        txtDzip = new javax.swing.JTextField();
        lblDonateFoodCity = new javax.swing.JLabel();
        comboCity = new javax.swing.JComboBox<>();
        lblDonateFoodWarehouse = new javax.swing.JLabel();
        comboWH = new javax.swing.JComboBox<>();
        btnSubmitDonation = new javax.swing.JButton();
        lblPersonMin = new javax.swing.JLabel();
        lblPersonMax = new javax.swing.JLabel();
        lblDonateFoodPerson = new javax.swing.JLabel();
        logoImage = new javax.swing.JLabel();
        LabelImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDonateTitle.setFont(new java.awt.Font("Lucida Handwriting", 1, 29)); // NOI18N
        lblDonateTitle.setForeground(new java.awt.Color(255, 93, 119));
        lblDonateTitle.setText("Donate Food ");
        add(lblDonateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        lblDonateFoodItem.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblDonateFoodItem.setText("Food Item :");
        add(lblDonateFoodItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        lblDonateFoodQty.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblDonateFoodQty.setText("Quantity :");
        add(lblDonateFoodQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        txtDonateFoodItem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDonateFoodItem.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDonateFoodItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDonateFoodItemFocusLost(evt);
            }
        });
        add(txtDonateFoodItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 200, -1));

        sdQuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sdQuan.setMajorTickSpacing(10);
        sdQuan.setMinimum(10);
        sdQuan.setPaintTicks(true);
        sdQuan.setAutoscrolls(true);
        add(sdQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        lblDonatePickupAdd.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        lblDonatePickupAdd.setText("Pickup Address");
        add(lblDonatePickupAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));

        chkAddress.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        chkAddress.setText("Same Address as in Profile");
        chkAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAddressActionPerformed(evt);
            }
        });
        add(chkAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        lblDonateFoodAddress.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblDonateFoodAddress.setText("Address :");
        add(lblDonateFoodAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        txtDadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDadd.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDaddFocusLost(evt);
            }
        });
        add(txtDadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 137, -1));

        lblPickupCity.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblPickupCity.setText("City :");
        add(lblPickupCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        txtDcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDcity.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDcityFocusLost(evt);
            }
        });
        add(txtDcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 137, -1));

        lblPickupState.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblPickupState.setText("State :");
        add(lblPickupState, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 60, 20));

        txtDstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDstate.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDstateFocusLost(evt);
            }
        });
        add(txtDstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 137, -1));

        lblPickupZipCode.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblPickupZipCode.setText("Zipcode :");
        add(lblPickupZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        txtDzip.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDzip.setPreferredSize(new java.awt.Dimension(150, 25));
        txtDzip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDzipFocusLost(evt);
            }
        });
        add(txtDzip, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 137, -1));

        lblDonateFoodCity.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblDonateFoodCity.setText("City :");
        add(lblDonateFoodCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 50, -1));

        comboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCityActionPerformed(evt);
            }
        });
        add(comboCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 200, -1));

        lblDonateFoodWarehouse.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblDonateFoodWarehouse.setText("Nearest Warehouse :");
        add(lblDonateFoodWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 160, -1));

        comboWH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboWH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWHActionPerformed(evt);
            }
        });
        add(comboWH, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 200, -1));

        btnSubmitDonation.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        btnSubmitDonation.setText("Donate");
        btnSubmitDonation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitDonationActionPerformed(evt);
            }
        });
        add(btnSubmitDonation, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 90, 40));

        lblPersonMin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPersonMin.setText("Min 10");
        add(lblPersonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        lblPersonMax.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPersonMax.setText("Max 100");
        add(lblPersonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        lblDonateFoodPerson.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDonateFoodPerson.setText("persons");
        add(lblDonateFoodPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));
        add(logoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 18, 102, 104));
        add(LabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 850));
    }// </editor-fold>//GEN-END:initComponents

      public void setBG() {
        try {
            LabelImage.setMinimumSize(new Dimension(1500, 1000));
            LabelImage.setPreferredSize(new Dimension(1500, 1000));
            LabelImage.setMaximumSize(new Dimension(1500, 1000));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(2500, 1000, java.awt.Image.SCALE_SMOOTH);
            LabelImage.setIcon(new ImageIcon(newimg));
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setLogo() {
        try {
            logoImage.setMinimumSize(new Dimension(100, 100));
            logoImage.setPreferredSize(new Dimension(100, 100));
            logoImage.setMaximumSize(new Dimension(100, 100));

            Image img = ImageIO.read(getClass().getResource("/Images/cmnlogo.jpeg"));

            Image newimg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            logoImage.setIcon(new ImageIcon(newimg));
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtDonateFoodItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDonateFoodItemFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDonateFoodItemFocusLost

    private void txtDaddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDaddFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtDaddFocusLost

    private void txtDcityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDcityFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtDcityFocusLost

    private void txtDstateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDstateFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtDstateFocusLost

    private void txtDzipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDzipFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtDzipFocusLost

    private void btnSubmitDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitDonationActionPerformed
        // TODO add your handling code here:
        if(!nullCheck()){
            Donation dt= new Donation();
            dt.setDonatId("1");
            dt.setDonatDname(donName);
            dt.setDonatFooditem(txtDonateFoodItem.getText());
            dt.setDonatFoodQuant(String.valueOf(sdQuan.getValue()));
            dt.setDonatPickuptype("Pick up");
            dt.setDonatStatus("Requested");
            dt.setDonatWHname(comboWH.getSelectedItem().toString());
            UserAccount ua=new UserAccount();
            ua.setUsername(userAcc.getUsername());
            ua.setPassword(userAcc.getPassword());
            dt.setDonatDonorAcc(ua);
            dt.setDonatAdd(txtDadd.getText());
            dt.setDonatCity(txtDcity.getText());
            donatD = ecosystem.getDonatDirectory();
            donatD.addNewDonation(dt);
            ecosystem.setDonatDirectory(donatD);
            
             //JOptionPane.showMessageDialog is used to create an information-message dialog titled "Message"
             //Message will be displayed after submit button as shown below

            JOptionPane.showMessageDialog(this, "Thank you for the donation! \n Your request has been placed. ");
            clearfields();
        }
        else{
            // fill all fields
            JOptionPane.showMessageDialog(this, "Please make sure that you have filled all the mandatory fields");
        }
    }//GEN-LAST:event_btnSubmitDonationActionPerformed

    private void comboCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCityActionPerformed
        // TODO add your handling code here:
        String city=comboCity.getSelectedItem().toString();
        ArrayList<String> whList = new ArrayList<String>();
        for (FCWarehouse fcw : ecosystem.getFCWDirectory().getFcwList()){
            if(fcw.getFcwCity().equals(city)){
                whList.add(fcw.getFcwName());
            }
        }         
        comboWH.setModel(new DefaultComboBoxModel<String>(whList.toArray(new String[0])));
    }//GEN-LAST:event_comboCityActionPerformed

    private void chkAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAddressActionPerformed
        // TODO add your handling code here:
        if(chkAddress.isSelected()){
            for(Donor d: ecosystem.getDonDir().getDonorList()){
                if(d.getDonUserName().equals(donUName)){
                    txtDadd.setText(d.getDonorAddres());
                    txtDcity.setText(d.getDonorCity());
                    txtDstate.setText(d.getDonorState());
                    txtDzip.setText(d.getDonorZipcode());
                }
            }
        }
        else{
            txtDadd.setText("");
            txtDcity.setText("");
            txtDstate.setText("");
            txtDzip.setText("");
        }
    }//GEN-LAST:event_chkAddressActionPerformed

    private void comboWHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboWHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JButton btnSubmitDonation;
    private javax.swing.JCheckBox chkAddress;
    private javax.swing.JComboBox<String> comboCity;
    private javax.swing.JComboBox<String> comboWH;
    private javax.swing.JLabel lblDonateFoodAddress;
    private javax.swing.JLabel lblDonateFoodCity;
    private javax.swing.JLabel lblDonateFoodItem;
    private javax.swing.JLabel lblDonateFoodPerson;
    private javax.swing.JLabel lblDonateFoodQty;
    private javax.swing.JLabel lblDonateFoodWarehouse;
    private javax.swing.JLabel lblDonatePickupAdd;
    private javax.swing.JLabel lblDonateTitle;
    private javax.swing.JLabel lblPersonMax;
    private javax.swing.JLabel lblPersonMin;
    private javax.swing.JLabel lblPickupCity;
    private javax.swing.JLabel lblPickupState;
    private javax.swing.JLabel lblPickupZipCode;
    private javax.swing.JLabel logoImage;
    private javax.swing.JSlider sdQuan;
    private javax.swing.JTextField txtDadd;
    private javax.swing.JTextField txtDcity;
    private javax.swing.JTextField txtDonateFoodItem;
    private javax.swing.JTextField txtDstate;
    private javax.swing.JTextField txtDzip;
    // End of variables declaration//GEN-END:variables

    private boolean nullCheck() {
        if(txtDonateFoodItem.getText().length()!=0 && txtDadd.getText().length()!=0 && txtDcity.getText().length()!=0 && 
                txtDstate.getText().length()!=0 && txtDzip.getText().length()!=0 )
        {
            return false;
        }
        else return true;
    }

    private void clearfields() {
        txtDonateFoodItem.setText("");
        txtDadd.setText("");
        txtDcity.setText("");
        txtDstate.setText("");
        txtDzip.setText("");
        comboCity.setSelectedIndex(0);
        comboWH.setSelectedIndex(0);
        sdQuan.setExtent(0);
        chkAddress.setSelected(false);
        comboCity.setSelectedIndex(0);
        comboWH.setSelectedIndex(0);
    }
}
