/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DonorRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import userinterface.FCAdminRole.FCAdminWorkAreaPanel;
import userinterface.MainJFrame;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author dristidani
 */
public class DonorAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorAreaJPanel
     */
    private JPanel userProcessContainer;

    private UserAccount userAccount;
    EcoSystem ecosystem;
    JPanel jp;
    JSplitPane jsp;

    public DonorAreaJPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount account, JPanel jp, JSplitPane jsp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        //valueLabel.setText(enterprise.getName());
        this.ecosystem = ecosystem;
        this.jp = jp;
        this.jsp = jsp;
        setBG();
        logoutlogo();
        setLogo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPaneDon = new javax.swing.JSplitPane();
        MenubarPanel = new javax.swing.JPanel();
        btnViewDonations = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        btnDonateNow = new javax.swing.JButton();
        lblWelcomeDonorTitle = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoImage = new javax.swing.JLabel();
        WorkAreaPanel = new javax.swing.JPanel();
        LabelImg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(2000, 1050));

        SplitPaneDon.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        MenubarPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenubarPanel.setPreferredSize(new java.awt.Dimension(617, 500));
        MenubarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewDonations.setBackground(new java.awt.Color(255, 93, 119));
        btnViewDonations.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnViewDonations.setText("View Donations");
        btnViewDonations.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonationsActionPerformed(evt);
            }
        });
        MenubarPanel.add(btnViewDonations, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 83, 150, 30));

        btnViewProfile.setBackground(new java.awt.Color(255, 93, 119));
        btnViewProfile.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });
        MenubarPanel.add(btnViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 83, 150, 30));

        btnDonateNow.setBackground(new java.awt.Color(255, 93, 119));
        btnDonateNow.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnDonateNow.setText("Donate Now");
        btnDonateNow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDonateNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateNowActionPerformed(evt);
            }
        });
        MenubarPanel.add(btnDonateNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 83, 150, 30));

        lblWelcomeDonorTitle.setFont(new java.awt.Font("Lucida Handwriting", 1, 29)); // NOI18N
        lblWelcomeDonorTitle.setForeground(new java.awt.Color(255, 93, 119));
        lblWelcomeDonorTitle.setText("! Welcome Donor !");
        MenubarPanel.add(lblWelcomeDonorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoutMousePressed(evt);
            }
        });
        MenubarPanel.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 42, 32));
        MenubarPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 0, -1, 130));
        MenubarPanel.add(logoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, 60));

        SplitPaneDon.setLeftComponent(MenubarPanel);

        WorkAreaPanel.setPreferredSize(new java.awt.Dimension(2000, 900));

        LabelImg.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
        WorkAreaPanel.setLayout(WorkAreaPanelLayout);
        WorkAreaPanelLayout.setHorizontalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WorkAreaPanelLayout.setVerticalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        SplitPaneDon.setRightComponent(WorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPaneDon, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

     public void setLogo() {
        try {
            logoImage.setMinimumSize(new Dimension(100, 100));
            logoImage.setPreferredSize(new Dimension(100, 100));
            logoImage.setMaximumSize(new Dimension(100, 100));

            Image img = ImageIO.read(getClass().getResource("/Images/cmnlogo.jpeg"));

            Image newimg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            logoImage.setIcon(new ImageIcon(newimg));
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    public void setBG() {
        try {
            LabelImg.setMinimumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setPreferredSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));
            LabelImg.setMaximumSize(new Dimension(userProcessContainer.getWidth(), userProcessContainer.getHeight()));

            Image img = ImageIO.read(getClass().getResource("/Images/blurbg.jpeg"));

            Image newimg = img.getScaledInstance(1500, userProcessContainer.getHeight(), java.awt.Image.SCALE_SMOOTH);
            LabelImg.setIcon(new ImageIcon(newimg));
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
            Logger.getLogger(DonorProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void logoutlogo() {

        try {
           
            lblLogout.setMinimumSize(new Dimension(50,60));
            lblLogout.setPreferredSize(new Dimension(50,60));
            lblLogout.setMaximumSize(new Dimension(50,60));
            
            Image img1 = ImageIO.read(getClass().getResource("/Images/Logout.png"));
            Image newimg1 = img1.getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);

            lblLogout.setIcon(new ImageIcon(newimg1));
            //IOException is the base class for thrown exceptions
            
        } catch (IOException ex) {
            Logger.getLogger(DonorAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void btnViewDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonationsActionPerformed
        // TODO add your handling code here:
        ViewDonationPanel objViewDon = new ViewDonationPanel(userProcessContainer, ecosystem, userAccount);
        //SplitPane is used to divide two components
        SplitPaneDon.setRightComponent(objViewDon);
    }//GEN-LAST:event_btnViewDonationsActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        DonorProfilePanel objDonProf = new DonorProfilePanel(userProcessContainer, ecosystem, userAccount);
        //SplitPane is used to divide two components
        SplitPaneDon.setRightComponent(objDonProf);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnDonateNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateNowActionPerformed
        // TODO add your handling code here:
        DonateNowPanel objDonNow = new DonateNowPanel(userProcessContainer, ecosystem, userAccount);
        //SplitPane is used to divide two components
        SplitPaneDon.setRightComponent(objDonNow);
    }//GEN-LAST:event_btnDonateNowActionPerformed

    private void lblLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MainJFrame mjf = new MainJFrame();
            mjf.logout(userProcessContainer, jp, jsp);
            //IOException is the base class for thrown exceptions
        } catch (IOException ex) {
            Logger.getLogger(FCAdminWorkAreaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblLogoutMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImg;
    private javax.swing.JPanel MenubarPanel;
    private javax.swing.JSplitPane SplitPaneDon;
    private javax.swing.JPanel WorkAreaPanel;
    private javax.swing.JButton btnDonateNow;
    private javax.swing.JButton btnViewDonations;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblWelcomeDonorTitle;
    private javax.swing.JLabel logoImage;
    // End of variables declaration//GEN-END:variables
}
